import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider";
import Navbar from "./components/Navbar";
import { SearchProvider } from "@/context/SearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-base-100 min-h-screen"
      >
        <AuthProvider>
          <SearchProvider >
            <Navbar />
            <div className="flex gap-6 p-2 lg:px-[10%]">
              {children}
            </div>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
